import nearley from "nearley";
// The grammar is generated by nearleyc from concurrency.ne (CommonJS module).
// eslint-disable-next-line @typescript-eslint/no-var-requires
import grammar from "./concurrency.js";

export type Task = { type: "task"; name: string };
/** Sequential composition (`;`) of two or more sub-expressions, in order. */
export type Sequential = { type: "seq"; operands: Expression[] };
/** Parallel composition (`||`) of two or more sub-expressions. */
export type Concurrent = { type: "par"; operands: Expression[] };
export type Expression = Task | Sequential | Concurrent;

export interface Constraint {
  /** task that must come before */
  before: string;
  /** task that must come after */
  after: string;
}

export interface Program {
  type: "program";
  expression: Expression;
  constraints: Constraint[];
}

// The compiled grammar is stateless and can be shared across parses; each
// `new Parser(...)` resets the (singleton) lexer, so this is safe to reuse.
const compiledGrammar = nearley.Grammar.fromCompiled(grammar as any);

/**
 * Parse a concurrency program: an expression built from tasks combined with
 * `;` (sequence) and `||` (parallel), optionally followed by newline-separated
 * `a < b` ordering constraints.
 *
 * Throws on a syntax error, or if the input is ambiguous (more than one parse).
 */
export function parseProgram(input: string): Program {
  const parser = new nearley.Parser(compiledGrammar);
  parser.feed(input);

  const results = parser.results as Program[];
  if (results.length === 0) {
    throw new Error("Unexpected end of input: incomplete program");
  }
  if (results.length > 1) {
    throw new Error(
      `Ambiguous parse: ${results.length} possible interpretations`
    );
  }
  return results[0];
}

export default parseProgram;
